[[web]]
== Web

Allows to configure an `io.vertx.ext.web.Route` in a declarative way, using `@org.jboss.weld.vertx.web.WebRoute` annotation.

.Artifact GAV
[source,xml]
----
<dependency>
  <groupId>org.jboss.weld.vertx</groupId>
  <artifactId>weld-vertx-web</artifactId>
  <version>${version.weld-vertx}</version>
</dependency>
----

=== Declaring routes in a declarative way

`weld-vertx-web` extends `weld-vertx-core` and `vertx-web` functionality and allows to automatically register `Route` handlers and observer methods discovered during container initialization.
In other words, it's possible to configure a `Route` in a declarative way - using `org.jboss.weld.vertx.web.WebRoute` annotation.
The target can be a class which implements `Handler<RoutingContext>`:

[source,java]
----
import org.jboss.weld.vertx.web.WebRoute;
import io.vertx.core.Handler;
import io.vertx.ext.web.RoutingContext;

@WebRoute("/hello") // Matches all HTTP methods
class HelloWorldHandler implements Handler<RoutingContext> {

    @Override
    public void handle(RoutingContext ctx) {
        ctx.response().setStatusCode(200).end("Hello world!");
    }
}
----

Or an observer method which observes `RoutingContext`:

[source,java]
----
import org.jboss.weld.vertx.web.WebRoute;
import io.vertx.ext.web.RoutingContext;

@ApplicationScoped
class HelloWorld {

    @WebRoute("/hello") // Matches all HTTP methods
    void hello(@Observes RoutingContext ctx) {
        ctx.response().setStatusCode(200).end("Hello world!");
    }
}
----

Constructed handler instances are not CDI contextual intances.
In other words, they're not managed by the CDI container (similarly as Java EE components like servlets).
However, dependency injection, interceptors and decorators are supported:

[source,java]
----
import static org.jboss.weld.vertx.web.WebRoute.HandlerType.BLOCKING;
import javax.inject.Inject;
import javax.enterprise.context.control.ActivateRequestContext;

@WebRoute("/hello", type = BLOCKING) // A blocking request handler
public class HelloHandler implements Handler<RoutingContext> {

    @Inject
    SayHelloService service;

    // Interceptor binding used to activate CDI request context within a handle() invocation
    @ActivateRequestContext
    @Override
    public void handle(RoutingContext ctx) {
        ctx.response().setStatusCode(200).end(service.hello());
    }
}
----

`@WebRoute` is a repeatable annotation.
 This means that multiple annotations may be declared on a handler class or an observer method.
 In this case, a handler instance or an observer method is used for multiple routes.

[source,java]
----
import org.jboss.weld.vertx.web.WebRoute;
import io.vertx.core.Handler;
import io.vertx.core.http.HttpMethod;
import io.vertx.ext.web.RoutingContext;

@WebRoute("/hello", methods = HttpMethod.GET)
@WebRoute("/bye")
public class SuperHandler implements Handler<RoutingContext> {

    @Override
    public void handle(RoutingContext ctx) {
        // This method will be invoked upon the same handler instance for both routes
        ctx.response().setStatusCode(200).end("I'm super!");
    }
}
----

[[web-howto]]
=== How does it work?

The central point of the module is the `org.jboss.weld.vertx.web.RouteExtension`.
Its primary task is to find all handler classes and observer methods annotated with `@WebRoute` and register routes through `RouteExtension.registerRoutes(Router)`.

`org.jboss.weld.vertx.web.WeldWebVerticle` extends `org.jboss.weld.vertx.WeldVerticle`, registers `RouteExtension` automatically, and also provides the `WeldWebVerticle.registerRoutes(Router)` method (which delegates to `RouteExtension`):

[source,java]
----
 class MyApp {

     public static void main(String[] args) {
         Vertx vertx = Vertx.vertx();
         WeldWebVerticle weldVerticle = new WeldWebVerticle();
         vertx.deployVerticle(weldVerticle, result -> {
             if (result.succeeded()) {
                 // Configure the router after Weld bootstrap finished
                 vertx.createHttpServer().requestHandler(weldVerticle.createRouter()::accept).listen(8080);
             }
         });
     }
 }
----
